In [1]:
import pandas as pd

In [2]:
path = r"C:\Users\Andrey\Downloads\Telegram Desktop\linesutm.txt"

In [10]:
df = pd.read_csv(path, sep=";", header=None, names=["LineNo", "E", "N", "Z"])
df

    LineNo           E            N      Z
0        1  432375.897  9787292.260 -0.542
1        1  432464.991  9787358.526 -0.542
2        2  432529.703  9787816.315 -0.542
3        2  432637.181  9787896.006 -0.542
4        3  432701.493  9788352.162 -0.542
5        3  432796.204  9788422.949 -0.542
6        4  432874.456  9788892.240 -0.542
7        4  432969.257  9788962.505 -0.542
8        5  433043.041  9789417.470 -0.542
9        5  433136.957  9789486.075 -0.542
10       6  433216.862  9789959.687 -0.542
11       6  433292.678  9790017.495 -0.542
12       7  433388.769  9790494.514 -0.542
13       7  433464.877  9790554.801 -0.542
14       8  433561.731  9791034.580 -0.542
15       8  433638.247  9791096.336 -0.542
16       9  433732.778  9791567.260 -0.542
17       9  433809.703  9791630.484 -0.542
18      10  433905.311  9792106.243 -0.542
19      10  433981.472  9792166.708 -0.542
20      11  431480.949  9784433.044 -0.542
21      11  435833.126  9798009.648 -0.542
22      12  431336.019  9783933.963 -0.542
23      12  435825.255  9797942.263 -0.542
24      13  431656.012  9785024.217 -0.542
25      13  435784.670  9797901.861 -0.542
26      14  431814.907  9785565.376 -0.542
27      14  435769.347  9797896.661 -0.542
28      15  431168.125  9783363.797 -0.542
29      15  435845.283  9797961.412 -0.542
30      16  432151.338  9786706.581 -0.542
31      16  435727.951  9797855.081 -0.542

In [12]:
lines = []

for i in range(len(df["LineNo"].unique())):
    buff = df[df["LineNo"]==i+1]
    line = (
        buff["E"].values,
        buff["N"].values
    )
    lines.append(line)

In [13]:
lines

[(array([432375.897, 432464.991]), array([9787292.26 , 9787358.526])),
 (array([432529.703, 432637.181]), array([9787816.315, 9787896.006])),
 (array([432701.493, 432796.204]), array([9788352.162, 9788422.949])),
 (array([432874.456, 432969.257]), array([9788892.24 , 9788962.505])),
 (array([433043.041, 433136.957]), array([9789417.47 , 9789486.075])),
 (array([433216.862, 433292.678]), array([9789959.687, 9790017.495])),
 (array([433388.769, 433464.877]), array([9790494.514, 9790554.801])),
 (array([433561.731, 433638.247]), array([9791034.58 , 9791096.336])),
 (array([433732.778, 433809.703]), array([9791567.26 , 9791630.484])),
 (array([433905.311, 433981.472]), array([9792106.243, 9792166.708])),
 (array([431480.949, 435833.126]), array([9784433.044, 9798009.648])),
 (array([431336.019, 435825.255]), array([9783933.963, 9797942.263])),
 (array([431656.012, 435784.67 ]), array([9785024.217, 9797901.861])),
 (array([431814.907, 435769.347]), array([9785565.376, 9797896.661])),
 (array([431168.125, 435845.283]), array([9783363.797, 9797961.412])),
 (array([432151.338, 435727.951]), array([9786706.581, 9797855.081]))]